MovieRecommendersystem/urls.py
from django.contrib import admin
from admins import views as admins
from django.urls import path
from users import views as usr 
from . import views as mainView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', mainView.index, name='index'),
    path("UserRegister/", mainView.UserRegister, name="UserRegister"),
    path("AdminLogin/", mainView.AdminLogin, name="AdminLogin"),
    path('index/', mainView.index, name='index'),
    path("UserLogin/", mainView.UserLogin, name="UserLogin"),

    ### User Side Views
    path("UserRegisterActions/", usr.UserRegisterActions, name="UserRegisterActions"),
    path("UserLoginCheck/", usr.UserLoginCheck, name="UserLoginCheck"),
    path("UserHome/", usr.UserHome, name="UserHome"),
    path("viewdata/", usr.viewdata, name="viewdata"),
    path("user_collaborating/", usr.user_collaborating, name="user_collaborating"),
    path("user_content_based/", usr.user_content_based, name="user_content_based"),


    ### Admin Side Views
    path("AdminLoginCheck/", admins.AdminLoginCheck, name="AdminLoginCheck"),
    path("AdminHome/", admins.AdminHome, name="AdminHome"),
    path("ViewRegisteredUsers/", admins.ViewRegisteredUsers, name="ViewRegisteredUsers"),
    path("AdminActivaUsers/", admins.AdminActivaUsers, name="AdminActivaUsers"),
    path("admin_viewdata_set/", admins.admin_viewdata_set, name="admin_viewdata_set"),
]

users/forms.py
from django import forms
from .models import UserRegistrationModel


class UserRegistrationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+', 'class': 'form-control'}),
                           required=True, max_length=100)

    loginid = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+', 'class': 'form-control'}),
                              required=True, max_length=100)

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'pattern': '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}', 'class': 'form-control',
                                          'title': 'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters'}),
        required=True, max_length=100)

    mobile = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[56789][0-9]{9}', 'class': 'form-control'}),
                             required=True,
                             max_length=100)

    email = forms.CharField(
        widget=forms.TextInput(attrs={'pattern': '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$', 'class': 'form-control'}),
        required=True, max_length=100)

    locality = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, max_length=100)

    address = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'cols': 20, 'class': 'form-control'}),
                              required=True, max_length=250)

    city = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only ',
               'class': 'form-control'}), required=True,
        max_length=100)

    state = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only ',
               'class': 'form-control'}), required=True,
        max_length=100)

    status = forms.CharField(widget=forms.HiddenInput(), initial='waiting', max_length=100)

    class Meta():
        model = UserRegistrationModel
        fields = '__all__'

assets/templates/AdminLogin.html
{% extends  'base.html' %}
{% load static %}

{% block title %}
    Admin Login
{% endblock %}
{% block admin_login %}
    active
{% endblock %}


{% block content %}
    <style>
        body {
            background: #fff;

        }

        .jumbotron {
            font-family: "Book Antiqua";
            margin-top: 130px;
            background: #fff;
            display: flex;
            vertical-align: center;
            height: 400px;
        }

        .card-body {
            
            width: 40%;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        }


    </style>

    <center>
        <div class="jumbotron">
            <div class="container">


                <div class="card card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <form action="{% url 'AdminLoginCheck' %}" method="POST" class="text-primary">
                                {% csrf_token %}
                                <legend style="float: right"> Admin</legend>
                                <br><br>
                                <br>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="text" class="form-control" name="loginid" required
                                               placeholder="Enter Login Id">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="password" class="form-control" name="pswd" required
                                               placeholder="Enter password">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <div class="col-md-12">

                                        <center>
                                            <input type="submit" class="btn btn-block btn-primary"
                                                   value="Sign in">
                                            &nbsp;
                                            <input type="reset" class="btn btn-block btn-dark">
                                        </center>
                                    </div>
                                </div>


                                <!-- Message -->
                                {% if messages %}
                                    {% for message in messages %}
                                        <p align="center" class="text-primary"> {{ message }}</p>
                                    {% endfor %}
                                {% endif %}


                            </form>

                        </div>
                    </div>
                </div>

            </div>

        </div>
    </center>



{% endblock %}

assets/templates/UserLogin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User Login{% endblock %}
{% block user_login %}active{% endblock %}

{% block content %}


    <style>
        body {
            background: #fff; 
        }

        .jumbotron {
            font-family: "Book Antiqua";
            margin-top: 130px;
            background: #fff;
            display: flex;
            vertical-align: center;
            height: 400px;
        }

        .card-body {
            
            width: 40%;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);

        }

    </style>
    <center>
        <div class="jumbotron">
            <div class="container">
                <div class="card card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <form action="{% url 'UserLoginCheck' %}" method="POST" class="text-primary">
                                {% csrf_token %}

                                <legend style="float: right"> User</legend>

                                <br> <br>
                                <br>

                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="text" class="form-control" name="loginname" required
                                               placeholder="Enter Login Id">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="password" class="form-control" name="pswd" required
                                               placeholder="Enter password">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="submit" class="btn btn-block  btn-primary" value="Sign in"> &nbsp;
                                        <input type="reset" class="btn btn-block btn-dark">

                                    </div>
                                </div>


                                <!-- Message -->
                                {% if messages %}
                                    {% for message in messages %}
                                        <p align="center" class="text-primary"> {{ message }}</p>
                                    {% endfor %}
                                {% endif %}

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </center>
{% endblock %}

assets/templates/UserRegistrations.html
{% extends 'base.html' %}

{% block content %}
<style>
    .row{
        margin-top: 50px;
    }
</style>

<main id="main">

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
        <div class="container">
            <!--
                        <div class="section-title">
                            <h2>User Registration Form</h2>
                        </div>
           -->
            <center>
                <div class="row" data-aos="fade-in">

                    <!--form -->

                    <div class="container width" id="register"class="fixed-top bg-black">
                        <div class="row card  card-body" style="background: rgb(248, 240, 240);">
                            <form action="{% url 'UserRegisterActions' %}" method="POST">


                                <div class="section-title">
                                    <legend style="color: black;">User Sign Up</legend>
                                    <br>
                                </div>
                                {% csrf_token %}

                                <div class="form-row">
                                    <div class="form-group col-md-4">
                                        <label for="id_name">User Name</label>
                                        {{ form.name }}
                                    </div>

                                    <div class="form-group col-md-4">
                                        <label for="id_loginid">Login Id</label>
                                        {{ form.loginid }}
                                    </div>


                                    <div class="form-group col-md-4">
                                        <label for="id_email">Email</label>
                                        {{ form.email }}
                                    </div>

                                    <div class="form-group col-md-4">
                                        <label for="id_mobile">Mobile</label>
                                        {{ form.mobile }}
                                    </div>


                                    <div class="form-group col-md-4">
                                        <label for="id_password">Password</label>
                                        {{ form.password }}
                                    </div>


                                    <div class="form-group col-md-4">
                                        <label for="id_locality">Locality</label>
                                        {{ form.locality }}
                                    </div>

                                </div>

                                <div class="form-row">
                                    <div class="form-group col-md-4">
                                        <label for="id_city">City</label>
                                        {{ form.city }}
                                    </div>

                                    <div class="form-group col-md-4">

                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="id_state">State</label>
                                        {{ form.state }}
                                    </div>
                                    <div class="form-group col-md-2">
                                        {# <label for="id_status">Status</label>#}
                                        {{ form.status }}
                                    </div>


                                    <div class="form-group col-md-8">
                                        <label for="id_address">Address </label>
                                        {{ form.address }}

                                    </div>


                                </div>

                                <br>
                                <button type="submit" class="btn btn-outline-dark">Sign up</button>
                                <button type="reset" class="btn btn-outline-dark">Reset</button>
                                <!-- Message -->
                                {% if messages %}
                                {% for message in messages %}
                                <p align="center" class="text-primary"> {{ message }}</p>
                                {% endfor %}
                                {% endif %}

                            </form>
                        </div>
                    </div>
                </div>
            </center>
        </div>
    </section><!-- End Contact Section -->

</main><!-- End #main -->

{% endblock content %}

assets/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title> Movie </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Dewi - v4.6.0
  * Template URL: https://bootstrapmade.com/dewi-free-multi-purpose-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <!-- <style>
    .bg-dark {
      background:  rgba(0,0,0,0.5) !important;
    }
  </style> -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top bg-dark">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="index.html"> Movie Recommender</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto" href="/">HOME</a></li>
          <li><a class="nav-link scrollto {% block user_login %}{% endblock %}" href="{% url 'UserLogin' %}">USER</a>
          </li>
          <li><a class="nav-link scrollto {% block admin_login %}{% endblock %}" href="{% url 'AdminLogin' %}">ADMIN</a>
          </li>
          <li><a class="getstarted scrollto" href="{% url 'UserRegister' %}">REGISTER</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
  {% block content %} {% endblock %}
  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span> Movie </span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/dewi-free-multi-purpose-html-template/ -->
        Designed by <a href="/">Alex Corparation</a>
      </div>
    </div>
  </footer>
  <!-- End Footer -->
  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

assets/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title> Movie </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Gp - v4.6.0
  * Template URL: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top bg-dark">
    <div class="container d-flex align-items-center justify-content-lg-between">

      <h1 class="logo me-auto me-lg-0"><a href="index.html"> Movie </span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'index' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'UserLogin' %}">User</a></li>
          <li><a class="nav-link scrollto" href="{% url 'AdminLogin' %}">Admin</a></li>
          <li><a class="nav-link scrollto " href="{% url 'UserRegister' %}">Register</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">

      

      

    </div>
  </section><!-- End Hero -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span> Movie</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-template/ -->
        Designed by <a href="/">Alex Corperations</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  
  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>